### PR TITLE
Fix xi-editor GPU switching

### LINKED ISSUE #238: Xi-mac forces mac to switch to high performance GPU
Launching xi-mac unconditionally switches my mbp to use the dedicated GPU, causing it to heat up and likely being at least partially the reason for #189 .

Alacritty has the same issue (since it also uses OpenGL for its rendering) and an easy looking solution is proposed [here](https://github.com/jwilm/alacritty/issues/210#issuecomment-271249897).

### PR DESCRIPTION
**Pull request by lukakerr**
This fixes #238 and #189 by adding attribute to not switch to dedicated GPU for macs that have an integrated GPU

### CODE REVIEW

**Comment by jansol** [comment]
LGTM

**Comment by jansol** [comment]
It did at least put my laptop back on its iGPU. Idle CPU & power usage still remains nontrivial but as established on IRC that's a separate issue.

**Comment by cmyr** [comment]
Okay, thanks for letting me know. I'll leave it up and see if @raphlinus wants to take a look, otherwise will merge in a few days.

**Comment by raphlinus** [comment]
For me the only question is whether any of the other points in [Supporting Multiple GPUs on Mac OS X](https://developer.apple.com/library/archive/technotes/tn2229/_index.html) are needed. If we're covered, I'm happy with this going in. Thanks for investigating!

I'd also be curious about actual effects on both performance and power usage. On my Gigabyte Aero 14 with 1070 and HD 630, I find that the 1070 actually uses _less_ power for things like scrolling, but it's complicated.

**Comment by jansol** [comment]
According to that, display reconfiguration needs to be dealt with (`CGDisplayRegisterReconfigurationCallback`). NSOpenGLView apparently handles that automatically but I didn't find any evidence that NSOpenGLLayer, which xi-mac uses, would do the same. Then again NSOpenGLLayer and its underlying CAOpenGLLayer are deprecated since macOS 10.15, along with OpenGL in general.

Triggering a switch to the dedicated GPU while xi-mac is running and back didn't cause any problems. Unless there's a possiblity that different monitors are driven by different GPUs, which I can't test. That should not be too different from triggering a GPU switch though so unless someone can test and report otherwise I'm fairly confident this can go in as-is.

**Comment by cmyr** [comment]
Okay, I'm happy to defer to @jansol and @lukakerr, thanks for looking into this!

**Pull request merged**
